# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import places.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', places.fields.PlacesField(blank=True, max_length=255)),
            ],
        ),
    ]
